version: "{build}"
build: off
environment:
  PYPI_USERNAME:
    secure: 20LVRUqPdKxWydU70DgLxA==
  PYPI_PASSWORD:
    secure: g599B1DPNusI9H8GYIq6yn4CiRsVMRqtDm9nyb7MEjQ=
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.6"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.7"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.8"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.9"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "python3"
      STACK: "3.10"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python310"
      PYTHON_VERSION: "3.10"
      PYTHON_ARCH: "32"
      STACK: "3.10"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python310-x64"
      PYTHON_VERSION: "3.10"
      PYTHON_ARCH: "64"
      STACK: "3.10"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "32"
      STACK: "3.9"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "64"
      STACK: "3.9"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "32"
      STACK: "3.8"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      STACK: "3.8"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
      STACK: "3.7"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      STACK: "3.7"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"
      STACK: "3.6"
      BASSLIB: "bass24"
      TAGSLIB: "tags18"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      STACK: "3.6"
      BASSLIB: "bass24\\x64"
      TAGSLIB: "tags18"

stack: python %STACK%

before_build:
  - ps: |
      if($isWindows)
      {
        $wc = New-Object System.Net.WebClient
        $wc.DownloadFile("http://www.un4seen.com/files/bass24.zip", (Join-Path ($pwd).path "bass24.zip"))
        $wc.DownloadFile("http://www.un4seen.com/files/z/3/tags18.zip", (Join-Path ($pwd).path "tags18.zip"))
        & 7z --% x bass24.zip -obass24 -r
        & 7z --% x tags18.zip -otags18 -r
      } else {
        & wget http://www.un4seen.com/files/bass24-linux.zip
        & wget http://www.un4seen.com/files/z/3/tags18-linux.zip
        & 7z --% x bass24-linux.zip -obass24-linux -r
        & 7z --% x tags18-linux.zip -otags18-linux -r
      }
      
install:
  - ps: |
      if($isWindows)
      {
        $version = &"$($env:PYTHON)\python.exe" -c --% "from Bass4Py import __version__; import sys; _ = sys.stdout.write(__version__)"
      } else {
        $version = & $($env:PYTHON) -c --% "from Bass4Py import __version__; import sys; _ = sys.stdout.write(__version__)"
      }
      Update-AppveyorBuild -Version "$($version)+$($env:APPVEYOR_BUILD_NUMBER)"
  - cmd: |
      %PYTHON%\python.exe --version
      %PYTHON%\Scripts\pip.exe --version
      %PYTHON%\python.exe -m pip install -r requirements-dev.txt
  - sh: |
      $PYTHON --version
      $PYTHON -m pip --version
      $PYTHON -m pip install -r requirements-dev.txt
build_script:
  - cmd: |
      %PYTHON%\\python.exe setup.py build_ext --inplace
      %PYTHON%\\python.exe setup.py bdist_wheel
  - sh: |
      $PYTHON setup.py build_ext --inplace
      $PYTHON setup.py bdist_wheel

before_test:
  - sh: |
      export LD_LIBRARY_PATH=$(pwd)/bass24-linux/x64/:$(pwd)/tags18-linux/x64/

test_script:
  - sh: |
      $PYTHON -m pytest --junitxml=junit.xml
  - cmd: |
      %PYTHON%\python.exe -m pytest --junitxml=junit.xml

on_finish:
  - ps: |
      $escapeparser = '--%'
      if (Test-Path "junit.xml")
      {
        if($isWindows)
        {
          $wc = New-Object 'System.Net.WebClient'
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Join-Path ($pwd).path "junit.xml"))
        } else {
          & curl $escapeparser -F "file=@junit.xml" "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
        }
      }

artifacts:
  - path: dist/*.whl

deploy:
  auth_token:
    secure: PFPMLUtwkaBjEP5FyQP3hgsHMRr5Uejw1eL6aOQKOIl1S1iAx1QcdVpmtZv/FKxC
  description: 'Bass4Py release, see changelog for more information'
  provider: GitHub
  artifact: dist/*.whl
  on:
    APPVEYOR_REPO_TAG: true

after_deploy:
  - ps: |
      Write-Output ("Deploying " + $env:APPVEYOR_REPO_TAG_NAME + " to PyPI...")
      &"${Env:PYTHON}/python.exe" -m pip install twine
      &"${Env:PYTHON}/python.exe" -m twine upload -u ${Env:PYPI_USERNAME} -p ${Env:PYPI_PASSWORD} --skip-existing dist/\*
